server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # git ²Ö¿âµØÖ·
          uri: https://github.com/Morgan412/weixin-order
          # ²Ö¿âÏÂµÄËÑË÷Â·¾¶
          search-paths: conf
          # git²Ö¿âÕËºÅ
          username:
          # git²Ö¿âÃÜÂë
          password:
